name: Python continuous integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10','3.11','3.12','3.13']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python:version: ${{ matrix.python_version }}
      - name: Install make tools
        run: |
          sudo apt update -y
          sudo apt install -y build-essential
      - name: Install dependencies alongside the development ones
        run: sudo make dev_install
      - name: Check for code writing errors
        run: sudo make lint
      - name: Launch unit test and displays the coverage result
        run: |
          sudo make test
          sudo make coverage